services:
  foundry:
    build: .
    container_name: foundry-vtt
    ports:
      - "30000:30000"
    volumes:
      - ./data:/home/foundry/data
    user: "${UID}:${GID}"
    restart: unless-stopped
